# Blinky cross-compilation policy using devkitARM's published ARM11 ABI.
# Public contract: devkitPro/cmake Platform/Nintendo3DS.cmake and GCC ARM options.
# Keep Generic here for compatibility with the pinned upstream dependency probes.
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(N3DS TRUE)
set(NINTENDO_3DS TRUE)
if(NOT DEFINED DEVKITPRO)
    set(DEVKITPRO "$ENV{DEVKITPRO}" CACHE PATH "devkitPro installation")
endif()
if(NOT IS_DIRECTORY "${DEVKITPRO}/devkitARM")
    message(FATAL_ERROR "Set DEVKITPRO to a directory containing devkitARM")
endif()
set(DEVKITARM "${DEVKITPRO}/devkitARM")
set(_blinky_suffix "")
if(CMAKE_HOST_WIN32)
    set(_blinky_suffix ".exe")
endif()
foreach(_mapping C:gcc CXX:g++ ASM:gcc AR:ar RANLIB:ranlib STRIP:strip)
    string(REPLACE ":" ";" _parts "${_mapping}")
    list(GET _parts 0 _kind)
    list(GET _parts 1 _program)
    if(_kind MATCHES "^(C|CXX|ASM)$")
        set(_key "CMAKE_${_kind}_COMPILER")
    else()
        set(_key "CMAKE_${_kind}")
    endif()
    set(${_key} "${DEVKITARM}/bin/arm-none-eabi-${_program}${_blinky_suffix}" CACHE FILEPATH "ARM tool" FORCE)
endforeach()
set(_blinky_arch "-march=armv6k -mtune=mpcore -mfloat-abi=hard -mtp=soft -mword-relocations")
set(_blinky_c "${_blinky_arch} -fno-fast-math -ffp-contract=off -ffunction-sections -fdata-sections -D_GNU_SOURCE -D__3DS__ -D_3DS -DARM11")
foreach(_language C CXX)
    set(CMAKE_${_language}_FLAGS_INIT "${_blinky_c}")
    set(CMAKE_${_language}_STANDARD_LIBRARIES "-lctru -lm" CACHE STRING "SDK runtime")
endforeach()
set(CMAKE_ASM_FLAGS_INIT "${_blinky_arch}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_blinky_arch} -specs=${DEVKITARM}/arm-none-eabi/lib/3dsx.specs -Wl,--gc-sections")
include_directories(SYSTEM "${DEVKITPRO}/libctru/include")
link_directories("${DEVKITPRO}/libctru/lib")
set(CMAKE_FIND_ROOT_PATH "${DEVKITARM}" "${DEVKITARM}/arm-none-eabi"
    "${DEVKITPRO}/libctru" "${DEVKITPRO}/portlibs/3ds")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
foreach(_kind LIBRARY INCLUDE PACKAGE)
    set(CMAKE_FIND_ROOT_PATH_MODE_${_kind} ONLY)
endforeach()
# Linking feature probes detects missing newlib functions; archive-only probes do not.
set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
set(CMAKE_REQUIRED_LIBRARIES ctru)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Static 3DS libraries" FORCE)